//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatID { get; set; }
        public string ChatTitle { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> User_Employee_ID { get; set; }
    }
}
