//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProject
    {
        public int EmployeeProjectID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
