//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string MessageText { get; set; }
        public string MessageDate { get; set; }
        public string MessageTime { get; set; }
        public byte[] MessageFile { get; set; }
        public string SenderTable { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> ChatID { get; set; }
        public Nullable<bool> hasSeen { get; set; }
    }
}
