//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string StartDate { get; set; }
        public string SuggestedDeadLine { get; set; }
        public string DeadLIne { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Abstract { get; set; }
        public string Title { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Link { get; set; }
        public string Tags { get; set; }
        public string KeyWords { get; set; }
    }
}
