//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SlideID { get; set; }
        public string BackgroundImg { get; set; }
        public string thumbnail { get; set; }
        public string Text { get; set; }
        public string Link { get; set; }
    }
}
